version: 0.2

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-2"
    HUGO_VERSION: "0.55.6"

phases:
  install:
    runtime-versions:
        docker: 18
    commands:
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo*
  build:
    commands:
      - hugo --source site
  post_build:
    commands:
      - aws s3 sync --delete ./site/public s3://BUCKETNAME --cache-control max-age=3600
