baseURL = "https://rodneyperez.dev"
title = "Miami Panic"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true


[params]
  author = "Rodney Perez"
  info = "Full Stack DevOps and Infrastructure"
  description = "Rodney Perez's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://rodneyperez.dev/headshot.jpeg"
  favicon_32="http://rodneyperez.dev/miami_panic.png"
  touchIcon ="http://rodneyperez.dev/miami_panic.png"


  footercontent = "Enter a text here."
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2021

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/RodneyPerez/"

[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'", "https://rodneyperez.dev"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com", "https://twemoji.maxcdn.com/v/13.0.2/twemoji.min.js"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]
